language: perl
perl:
  - "5.16"
  - "5.10"
env:
  - PERL_CPANM_OPT="-v --mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --mirror http://cpan.mirrors.travis-ci.org --cascade-search --notest --force --skip-satisfied --no-interactive"
before_install:
  - cpanm -n Module::Install Catalyst::Devel Text::CSV JSON::Any MooseX::Types::JSON
  - cpanm -n DBIx::Class
  - cpanm -n App::Sqitch
  - cpanm -n DBIx::Class::Optional::Dependencies
  - cpanm -n Catalyst::Plugin::Assets
before_script:
  - psql -c 'create database iota_production' -U postgres
  - sqitch -d iota_production deploy
notifications:
  irc:
    channels:
      - "chat.freenode.net#iota"
